# Generated by Django 3.0.6 on 2020-05-19 12:29

from django.db import migrations


def create_first_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    t = Tenant()
    t.save()

    User = apps.get_model("big_eggs_auth", "User")
    first_user = User.objects.first()
    if first_user:
        t.users.add(User.objects.first())


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_first_tenant),
    ]
