# Generated by Django 3.0.6 on 2020-05-19 11:37

from django.db import migrations


def fill_with_first_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    tenant = Tenant.objects.first()  # this tenant will be inserted on every object

    Egg = apps.get_model("chicken", "Egg")
    ChickenGroup = apps.get_model("chicken", "ChickenGroup")
    Chicken = apps.get_model("chicken", "Chicken")

    print()
    print("Eggs updated: ", Egg.objects.all().update(tenant=tenant))
    print("ChickenGroup updated: ", ChickenGroup.objects.all().update(tenant=tenant))
    print("Chicken updated: ", Chicken.objects.all().update(tenant=tenant))


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0008_auto_20200519_1336"),
        ("tenants", "0002_auto_20200519_1429"),
    ]

    operations = [
        migrations.RunPython(fill_with_first_tenant),
    ]
