# Generated by Django 3.0.7 on 2020-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0010_auto_20200519_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="egg",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
