# Generated by Django 3.0.7 on 2020-06-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0014_chickengroup_selectable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chickengroup",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="chickengroup",
            name="selectable",
            field=models.BooleanField(
                default=True,
                help_text="Gruppe auswählbar bei der Eingabe von Eiern?",
                verbose_name="Auswählbar",
            ),
        ),
    ]
