# Generated by Django 3.0.7 on 2020-06-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0016_auto_20200622_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="error",
            field=models.CharField(
                choices=[
                    ("N", "keine"),
                    ("B", "Bauchei"),
                    ("D", "Doppeldotter"),
                    ("E", "Ei im Ei"),
                    ("A", "Kalkablagerungen"),
                    ("K", "Knickei"),
                    ("W", "Windei"),
                    ("S", "Sparei"),
                    ("P", "Spurei"),
                    ("Z", "Zerstört"),
                ],
                default="N",
                max_length=1,
                verbose_name="Fehler",
            ),
        ),
    ]
