# Generated by Django 3.0.8 on 2020-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0017_auto_20200622_1345"),
    ]

    operations = [
        migrations.AddField(
            model_name="egg",
            name="size",
            field=models.CharField(
                choices=[
                    ("N", "---"),
                    ("S", "Klein: < 53g"),
                    ("M", "Mittel: 53 =< 63g"),
                    ("L", "Groß: 63 =< 73g"),
                    ("X", "Sehr groß: > 73g"),
                ],
                default="N",
                max_length=1,
                verbose_name="Größe",
            ),
        ),
    ]
