# Generated by Django 3.0.9 on 2020-08-07 20:49

from django.db import migrations, models

import chicken.utils


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0018_egg_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chickengroup",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="egg",
            name="laid",
            field=models.DateTimeField(
                default=chicken.utils.today_midnight, verbose_name="Legedatum"
            ),
        ),
        migrations.AlterField(
            model_name="egg",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Anzahl"),
        ),
        migrations.AlterField(
            model_name="egg",
            name="size",
            field=models.CharField(
                choices=[
                    ("N", "---"),
                    ("S", "S: < 53g"),
                    ("M", "M: 53 =< 63g"),
                    ("L", "L: 63 =< 73g"),
                    ("X", "XL: > 73g"),
                ],
                default="N",
                max_length=1,
                verbose_name="Größe",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="egg",
            unique_together=set(),
        ),
    ]
