# Generated by Django 3.0.9 on 2020-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0019_auto_20200807_2249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="size",
            field=models.CharField(
                choices=[
                    ("N", "---------"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("X", "XL"),
                ],
                default="N",
                max_length=1,
                verbose_name="Größe",
            ),
        ),
    ]
